### ISSUE TITLE
Pip install with python 2.7 fails 

### ISSUE THREAD

**Issue by mpcarl** [NVIDIA/vagrant-swift-all-in-one#120]
Seeing this error when running `vagrant up --provision` for the first time
==> default: The URL you are using to fetch this script has changed, and this one will no
==> default: longer work. Please use get-pip.py from the following URL instead:
==> default:
==> default:     https://bootstrap.pypa.io/pip/2.7/get-pip.py
==> default:
==> default: Sorry if this change causes any inconvenience for you!
 
Was changed via issue #116, but looks to have changed again.

**Comment by tipabu** [comment]
Fix merged.
