### ISSUE TITLE
Build jerasure/gf-complete

### ISSUE THREAD

**Issue by clayg** [NVIDIA/vagrant-swift-all-in-one#56]
... at least add support to `reec` if they're checked out - like we do for `isa-l`:

https://github.com/swiftstack/vagrant-swift-all-in-one/blob/cfd62a21e3d048aaee0bfedd28ac88291676b08e/bin/reec#L3

Something like this:

https://review.openstack.org/#/c/408286/1/tools/pip-install-with-liberasurecode.sh

**Comment by tipabu** [comment]
Given the state of jerasure, I think we can just close this. See http://web.eecs.utk.edu/~jplank/plank/www/software.html
